// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SolveoDashboardAssignment.Api.Data;

#nullable disable

namespace SolveoDashboardAssignment.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SolveoDashboardAssignment.Api.Entities.ChannelPerformance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AvgSessionDurationSec")
                        .HasColumnType("integer");

                    b.Property<decimal>("BounceRate")
                        .HasColumnType("numeric");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("ConversionRate")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("Month")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("PagesPerSession")
                        .HasColumnType("numeric");

                    b.Property<int>("Sessions")
                        .HasColumnType("integer");

                    b.Property<int>("Signups")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("ChannelPerformances");
                });

            modelBuilder.Entity("SolveoDashboardAssignment.Api.Entities.KeywordPerformance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("AiOverviewTriggered")
                        .HasColumnType("boolean");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("ConversionRate2024")
                        .HasColumnType("numeric");

                    b.Property<decimal>("ConversionRate2025")
                        .HasColumnType("numeric");

                    b.Property<decimal>("CpcUsd")
                        .HasColumnType("numeric");

                    b.Property<int>("DifficultyScore")
                        .HasColumnType("integer");

                    b.Property<string>("Keyword")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Position2024")
                        .HasColumnType("integer");

                    b.Property<int>("Position2025")
                        .HasColumnType("integer");

                    b.Property<int>("PositionChange")
                        .HasColumnType("integer");

                    b.Property<int>("Signups2024")
                        .HasColumnType("integer");

                    b.Property<int>("Signups2025")
                        .HasColumnType("integer");

                    b.Property<int>("Traffic2024")
                        .HasColumnType("integer");

                    b.Property<int>("Traffic2025")
                        .HasColumnType("integer");

                    b.Property<decimal>("TrafficChangePct")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("KeywordPerformances");
                });

            modelBuilder.Entity("SolveoDashboardAssignment.Api.Entities.MonthlyMetrics", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("ChurnRate")
                        .HasColumnType("numeric");

                    b.Property<decimal>("ChurnedMrr")
                        .HasColumnType("numeric");

                    b.Property<decimal>("ExpansionMrr")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("Month")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("MrrUsd")
                        .HasColumnType("numeric");

                    b.Property<decimal>("NetNewMrr")
                        .HasColumnType("numeric");

                    b.Property<int>("PaidConversions")
                        .HasColumnType("integer");

                    b.Property<decimal>("SignupToTrialRate")
                        .HasColumnType("numeric");

                    b.Property<decimal>("TrialToPaidRate")
                        .HasColumnType("numeric");

                    b.Property<int>("TrialsStarted")
                        .HasColumnType("integer");

                    b.Property<int>("UniqueSignups")
                        .HasColumnType("integer");

                    b.Property<int>("WebsiteTraffic")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("MonthlyMetrics");
                });

            modelBuilder.Entity("SolveoDashboardAssignment.Api.Entities.RegionalPerformance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("CacUsd")
                        .HasColumnType("numeric");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("LtvUsd")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("Month")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("MrrUsd")
                        .HasColumnType("numeric");

                    b.Property<int>("OrganicTraffic")
                        .HasColumnType("integer");

                    b.Property<int>("PaidConversions")
                        .HasColumnType("integer");

                    b.Property<int>("PaidTraffic")
                        .HasColumnType("integer");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TotalTraffic")
                        .HasColumnType("integer");

                    b.Property<decimal>("TrialToPaidRate")
                        .HasColumnType("numeric");

                    b.Property<int>("TrialsStarted")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("RegionalPerformances");
                });
#pragma warning restore 612, 618
        }
    }
}
